# NOTE: this Dockerfile needs to be run from one-level up so that
# we get the examples docker-compose.yml files. Use 'make build/tester'
# in the makefile at the root of this repo and everything will work

FROM anaxexperience/alpine:3.7

RUN apk update \
    && apk add nodejs python3 openssl bash curl docker
RUN npm install -g json

# the Compose package in the public releases doesn't work on Alpine
RUN pip3 install docker-compose==1.10.0

COPY examples/compose/docker-compose.yml /src/examples/compose/docker-compose.yml

COPY test/compose.sh /src/compose.sh